Fliplet/fliplet-widget-dynamic-lists

js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

...as indicated by @hcarneiro
Ref. https://github.com/Fliplet/fliplet-studio/issues/2846

Removes typo

---

js/layout-javascript/news-feed-code.js

- Used `Fliplet.Session` information to compare the user emails to check if comments belong to current user.
- Works with SAML2
- `sendComments()` uses `Fliplet.Profile.Content` however the code doesn't rely on that information because it is just simpler to use the `Fliplet.Session` information for comparisson

Updated way to verify the current user

---

js/interface.js

Fixes - https://github.com/Fliplet/fliplet-studio/issues/2934

Fixes issue 2934

---

css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css
js/build.templates.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js
templates/build/small-card-profile-icon.build.hbs
templates/build/small-card-user-profile.build.hbs

- Fixes some styling issues on the search bar of the list styles
- Fixes My Profile on the Directory list style
- Fixes weird margin that can happen when is expanded

Tweaks and fixes

---

js/interface.js

Ref: https://github.com/Fliplet/fliplet-studio/issues/3139

Adds "None" option when columns are refreshed

---

css/layout-css/agenda-style.upload.css
js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

ref: https://github.com/Fliplet/fliplet-studio/issues/3180
ref: https://github.com/Fliplet/fliplet-studio/issues/3190

Fix several issues

---

widget.json

Ref: https://github.com/Fliplet/fliplet-studio/issues/3240

Missing link references

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Ref: https://github.com/Fliplet/fliplet-studio/issues/3242

Make sure we can always split via a comma

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

**Before:** When tapping on multiple filters, it would display the entry(ies) that would match **at least one or more** of the filters selected.
**After:** When tapping on multiple filters, it will display the entry(ies) that will **only** matches **all** of the filters selected.
Ref: https://github.com/Fliplet/fliplet-studio/issues/3290

Change filters to AND instead of OR

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Ref: https://github.com/Fliplet/fliplet-studio/issues/3290

Fix filters

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

Reviewed after an issue almost prevented a Freshfields app from launching.
Please make sure the other LFD layout JS code are reviewed in the same way as well.

Review comments

---

css/layout-css/agenda-style.upload.css
css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css
css/layout-css/small-h-card-style.upload.css
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

Issue reference: https://github.com/Fliplet/fliplet-studio/issues/3352

Fixes issue with webview after closing the keyboard on the comments

---

css/layout-css/small-card-style.upload.css
css/layout-css/small-h-card-style.upload.css

Issue reference: https://github.com/Fliplet/fliplet-studio/issues/3440

Removes top space if no image is displayed

---

js/default-configs/layouts-config.js
js/interface.js
js/interface.templates.js
templates/interface/detail-view-panels.interface.hbs

Issue reference: https://github.com/Fliplet/fliplet-studio/issues/3453

Fix misconfiguration of detail view fields

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

Issue ref: https://github.com/Fliplet/fliplet-studio/issues/3442
Solution comes from removing accents from letters, for comparison.
Solution saw here: https://stackoverflow.com/questions/990904/remove-accents-diacritics-in-a-string-in-javascript
Since the word for sorting is saved in a temp key, we can modify it without destroying the original value.

Next level sorting - Accented characters

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

```js
Fliplet.Hooks.on('flListDataBeforeDeleteConfirmation', function onBeforeDeleteEntry(data) {
// data - (Object) Contains "entryId", "config", "container"
// data.entryId - (Number) ID of the entry that is going to be deleted
// data.config - (Object) Entire configuration object of the component
// data.container - (Object) DOM element of the container of the component
// Resolve Promise
return Promise.resolve();
});
```
```js
Fliplet.Hooks.on('flListDataBeforeDeleteEntry', function onBeforeDeleteEntry(data) {
// data - (Object) Contains "entryId", "config", "container"
// data.entryId - (Number) ID of the entry that is going to be deleted
// data.config - (Object) Entire configuration object of the component
// data.container - (Object) DOM element of the container of the component …
```

Added Hooks before Adding, Editing, and Deleting entries

---

interface.html
js/default-configs/layouts-config.js
js/interface.js
js/layout-javascript/small-card-code.js

Issue reference: https://github.com/Fliplet/fliplet-studio/issues/3447#issuecomment-437954853
1. Fixes detail fields settings issue where the locked fields would disappear
2. Fixes an issue that wouldn't render the details correctly if the list was also displaying a logged in user's profile

Fix detail issues

---

css/interface.css
interface.html
js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

This adds an ID to the settings UI and exposes the component ID on the hooks.
Enhancement made to make easy for CS to train clients on how to use Hooks to target specific LFDs on a page.

Adds ID to settings UI and exposes ID in hooks

---

css/layout-css/agenda-style.upload.css
css/layout-css/news-feed-style.upload.css
js/interface.js

Issue reference: https://github.com/Fliplet/fliplet-e2e-tests/issues/197

Fixes & tweaks

---

js/layout-javascript/small-card-code.js

Fix reference: https://github.com/Fliplet/fliplet-studio/issues/3517

Fixes filtering that would ignore empty string fields

---

css/interface.css

This reverts commit 27f4ba9b4c7c2e39555a79724e00e8f3c0fcc701.

Revert "Revert "Updates setting's styles""

---

js/interface-lists.js
js/interface.js
js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

- Fixes an issue that would prevent a user to select a folder if the field was just created
- Fixes an issue that could cause duplicated entries when setting more than one field with image type
Feedback sheet: https://docs.google.com/spreadsheets/d/1bDJxRUcS6JSGhuJoa3KO_mSKi2dfce5QeiBmhNEOXr0/edit#gid=0

Fixes based on testing feedback

---

css/interface.css
interface.html
js/interface-lists.js
js/interface.js
js/interface.templates.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
templates/interface/folder-options.interface.hbs

- Fixes UI bugs when switching on and off the permissions' settings
- New fields to select folder for comments' user's photo
- Get the file from folder on the two styles that have comments

Fixes and improvements for comments

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

Ref. 3645
Changed the default date format on the LFD from `JAN 14th 2019` to `14 January 2019` by CS request.

Changed date format on LFD

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

This will fix an issue that would prevent the list from rendering when the device is offline.

Only get columns if detailViewAutoUpdate is true and device is online

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

Ref. Fliplet/fliplet-api#3078
Ref. Fliplet/fliplet-studio#3696
LFD item deletion will now wait for acknowledgement before returning control to the user.

LFD will now wait for acknowledgement for delete

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

Commenting wasn't working on the CX121 due to an exception being thrown due to missing Emails of some users.
Ref. https://github.com/Fliplet/fliplet-studio/issues/3748

Added a fix for users without emails when commenting

---

js/layout-javascript/news-feed-code.js

https://github.com/Fliplet/fliplet-studio/issues/3748

Fixed comments in 1.1.0

---

js/layout-javascript/news-feed-code.js

https://github.com/Fliplet/fliplet-studio/issues/3748

Fixed comments in 1.2.0

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

https://github.com/Fliplet/fliplet-studio/issues/3748

Fixes comments in 1.3.0

---

css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css

Ref. https://github.com/Fliplet/fliplet-studio/issues/3934
Applies to simple list and news feed layouts

Tweaks social toolbar styles to prevent line breaks

---

widget.json

follows https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/115

new syntax for skipping compile

---

css/layout-css/news-feed-style.upload.css

Ref. https://github.com/Fliplet/fliplet-studio/issues/3983

Adjusts z-index to ensure news feed content is not hidden

---

css/layout-css/small-card-style.upload.css

Issue ref: https://github.com/Fliplet/fliplet-studio/issues/3995

Fixes bookmark button position when card has no image

---

css/layout-css/small-card-style.upload.css

Issue ref: https://github.com/Fliplet/fliplet-studio/issues/3995

Changed position of the bookmark icon

---

css/layout-css/news-feed-style.upload.css

Reverts the following PRs:
- https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/113
- https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/118

Reverts fixes for overflown news feed summary

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

...unless options.silent is truthy.

Adds a toast warning if no entry is found for deep links

---

css/layout-css/news-feed-style.upload.css

Ref. https://github.com/Fliplet/fliplet-studio/issues/3993

Reduces specifity to ensure theme settings applied correctly

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

ref https://github.com/Fliplet/fliplet-studio/issues/3967
---

Avoids adding authentication multiple times

---

css/layout-css/small-card-style.upload.css

Follow-up from https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/123 (this time applied to a different layout.)

Reduces specificity to ensure theme settings applied correctly

---

js/layout-javascript/agenda-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4030
- Ensures non-ISO date formats are approximately treated in the Agenda layout
- Make Agenda more tolerant to varying date formats

Improve support for varying date formats in Agenda

---

css/layout-css/news-feed-style.upload.css
css/layout-css/small-card-style.upload.css

Ref. https://github.com/Fliplet/fliplet-studio/issues/3853
This should fix the issue above. And done in a way that doesn't re-introduce https://github.com/Fliplet/fliplet-studio/issues/3983

Fixes issue with Safari where content is not clipped through border radius

---

css/layout-css/small-card-style.upload.css

Follows https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/127

Ensures content is correctly clipped for small card overlays on tablets

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

Otherwise, this error is generated and commenting doesn't work

Fixes issue where user name/nickname is empty and breaks the commenting feature

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4098

Searches data correctly when cell contains a comma separated list of values

---

js/layout-javascript/news-feed-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4032

Ensures MixItUp is initialized correctly for the News Feed layout

---

js/layout-javascript/agenda-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4030

Ensures dates are correctly converted for all timezones

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4143

Ignores data source entries that have empty arrays for the image

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4032

Turns off MixItUp animation for a more performant bookmark filter

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

ref https://github.com/Fliplet/fliplet-studio/issues/3965

adds global and insensitive modifiers to regexps

---

js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4244

Ensures all filters are verified when filtering records

---

js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4080

Allows spaces at the end of search terms

---

js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4248

Skip conversion of null value

---

js/interface.js

Issue ref: https://github.com/Fliplet/fliplet-studio/issues/4260

Allow filter options to be sorted

---

js/interface.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4279

Better handling of duplicated field selections in summary & detail views

---

js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4264

Ensures number comparisons are correctly processed in filter conditions

---

js/layout-javascript/news-feed-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4294

Ensures bookmark and filters are reinitialised after search is cleared

---

js/interface.js
js/interface.templates.js
js/utils.js
templates/interface/filter-panels.interface.hbs
templates/interface/sort-panels.interface.hbs

Ref. https://github.com/Fliplet/fliplet-studio/issues/4263

Make sure filter logic is rendered consistently when loading/adding filters

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/small-h-card-code.js

Three LFD layouts were missing an important part of the code that analysed the `pvPreviousScreen` function.

Missing eval() on three layouts

---

js/utils.js

Follows https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/159

Adds backtick to symbol removal

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4327
The **Test** item below was created with a date value `2019-06-11T00:00:00+01:00 `.

Increase tolerance for different date formats when grouping agenda items

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Merging into `feat/filter-rebuild` for https://github.com/Fliplet/fliplet-studio/issues/4343
Ref. https://github.com/Fliplet/fliplet-studio/issues/4332

Set filter controls based on its own content

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4345

Sanitizes CSV before rendering

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4345

Only sanitizes columns used for filters

---

js/interface.js
widget.json

Ref. https://github.com/Fliplet/fliplet-studio/issues/4414

Ensures data view folders are correct referenced and copied when cloning apps

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js
js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4402
Also implements the following from https://github.com/Fliplet/fliplet-studio/issues/4371
> LFD is updated to verify admins by checking for arrays when verifying admin status

Ensure users can add/edit/delete own entries as configured

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4403

Ignore missing fields when displaying comment authors

---

interface.html
js/interface.js
js/interface.templates.js
templates/interface/detail-view-panels.interface.hbs
templates/interface/folder-options.interface.hbs
templates/interface/summary-view-panels.interface.hbs
widget.json

Ref. https://github.com/Fliplet/fliplet-studio/issues/4448

Remove root app/organization folder selection

---

js/interface.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4448

Ensures folder selection button is correctly shown

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js
js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4449

Allow URLs as images without needing any files in the selected folder

---

js/interface.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4482

Ensure detail view options remain the same when loading LFD configurations

---

css/layout-css/news-feed-style.upload.css
css/layout-css/small-card-style.upload.css

Ref. https://github.com/Fliplet/fliplet-studio/issues/4512
Fixes the 2 following issues.

Corrects border radius for small card and news feed layouts

---

js/interface.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4514#issuecomment-501681512

Prevent image data type field selection when loading a hidden image field

---

css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/query-parser.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4563

Use "dynamicListOpenSingleEntry" to open an entry if search results only return one result

---

js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4684

Ensures moment helper works correct with the plaintext helper

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4431

Use toast messages instead of popups for errors when commenting

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js
js/utils.js

ref https://github.com/Fliplet/fliplet-studio/issues/4769
---
Tested.

allow link action to read from array; refactor to utils

---

js/interface.js

@squallstar 
fixed file and search filters 4230
ref https://github.com/Fliplet/fliplet-studio/issues/4230
video: https://cl.ly/534f5ac8117f

Avoid the same fields from being selected multiple times for filter & search

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4772

Re-introduce support for limiting entries to 0 on initial load

---

js/utils.js

ref https://github.com/Fliplet/fliplet-studio/issues/4796

authenticate media urls before opening them

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4799

Skip an execution loop to allow custom handlers on filters

---

js/interface.js

Fixed "List search" and "List filters" fields become unclickable for the second time click on it.
ref https://github.com/Fliplet/fliplet-studio/issues/4231
video: https://cl.ly/880abb2013ed

Ensure search and filter field list is clickable after selecting a data field

---

js/layout-javascript/small-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4890

Ensure the "My profile" icon is correctly displayed

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4962

Prevent errors with overlay observers when bookmarks are disabled

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4962

Ensure legacy PV-based queries are processed correctly

---

css/interface.css
js/interface-lists.js

https://github.com/Fliplet/fliplet-studio/issues/4877
Added error highlighting for panel and 'Data view settings' button

Highlighting panel and 'Data view settings' button to show where error occurred

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4989

Validate and process date fields correctly in case it's not configured as the "Full Date" field

---

js/layout-javascript/agenda-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4989

Order agenda items by date before placing them in date groups

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4717

Keep filters and searches when reloading the page or returning via BACK

---

js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5115

Show a record if it matches any of the selected filter values

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5136

Improves error handling when adding or editing entries

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

Fliplet/fliplet-studio#5083
Added trim to comment.

Ensure users cannot send comments with only spaces 

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js
js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5180
```js
Fliplet.Hooks.on('flListDataAfterGetData', function(options) {
_.forEach(options.records, function(record) {
// Add new classes to the record container
_.set(record, 'data.flClasses', 'text-danger text-muted');
//_.set(record, 'data.flClasses', ['text-danger', 'text-muted']);
});
});
Fliplet.Hooks.on('flListDataBeforeRenderList', function(options) {
options.records.pop(); // Removes the last record
});
Fliplet.Hooks.on('flListDataAfterRenderList', function(options) {
console.log('flListDataAfterRenderList', options);
});
Fliplet.Hooks.on('flListDataBeforeRenderFilters', function(options) {
options.filters.pop(); // Removes the last filter
options.filters[0].data.pop(); // Removes the last value for the first filter
// Add a …
```

Adds new hooks for customizing LFD list and filters

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5174

Only load default data if there's no data source selected

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5180

Ensure default data and custom data are loaded with the same behavior

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5305

Ensure filters are added before continuing with rendering

---

js/layout-javascript/agenda-code.js

Fliplet/fliplet-studio#4973
Added page context update. If the user goes to the default page context is removed.

Show users the date as they left the agenda when users return to the page

---

js/interface-lists.js

Fliplet/fliplet-studio#4498
Added omit page property.

Current page is not added to link provider dropdown 

---

interface.html

The feature notice is creating pressure on CS while there isn't a schedule for R&D to work on this feature at this stage.

Removes feature notice

---

build.html

Ref. https://github.com/Fliplet/fliplet-studio/issues/5469

Ensures close icons are applied to LFD layouts when custom JS is enabled

---

js/interface-lists.js

https://github.com/Fliplet/fliplet-studio/issues/5439#issuecomment-569306562
Show error to the user if he doesn't fill all needed fields

Show error to the user if he doesn't fill all needed fields

---

js/layout-javascript/small-card-code.js

https://github.com/Fliplet/fliplet-studio/issues/5155
Added check if collapseTarget has offset method.

Fixed collapse target error

---

css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css

Ref. https://github.com/Fliplet/fliplet-studio/issues/5568

Force hidden filter and search UI to use relative position for more stable animation

---

js/interface-lists.js

https://github.com/Fliplet/fliplet-studio/issues/5439#issuecomment-575641157
Users will see all management errors at once

Users will see all management errors at once

---

css/layout-css/agenda-style.upload.css
css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css
js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Follows https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/299 (Requires https://github.com/Fliplet/fliplet-api/pull/3847)

Fixes issues with Agenda filters

---

css/layout-css/agenda-style.upload.css

Ensure bookmark toggle is visible next to circle menu

---

css/layout-css/agenda-style.upload.css
js/layout-javascript/agenda-code.js

* https://github.com/Fliplet/fliplet-studio/issues/5707
* https://github.com/Fliplet/fliplet-studio/issues/5715
* https://github.com/Fliplet/fliplet-studio/issues/5717
* https://github.com/Fliplet/fliplet-studio/issues/5716
* https://github.com/Fliplet/fliplet-studio/issues/5712
* https://github.com/Fliplet/fliplet-studio/issues/5710
* https://github.com/Fliplet/fliplet-studio/issues/5708

Fixes various QA issues with Agenda search and filter features

---

css/layout-css/agenda-style.upload.css

https://github.com/Fliplet/fliplet-studio/issues/5715

Ensure agenda is full screen to the bottom edge of iPhone X

---

css/layout-css/agenda-style.upload.css

https://github.com/Fliplet/fliplet-studio/issues/5715
Tested with:
- Studio and native device
- iPhone X and iPhone 8
- Top bar menu, bottom bar menu and circle menu

Fixes bookmark toggle location when using iPhone X

---

js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5750

Handle arrays appropriately if the field is used as an image field

---

css/layout-css/agenda-style.upload.css

Ref. https://github.com/Fliplet/fliplet-studio/issues/5761

Ensure filter/search bar is covered up when filter overlay is used in Agenda

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5861

Fixes an issue where social features are initialised multiple times

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5930 https://github.com/Fliplet/fliplet-studio/issues/6009

Ensure Fliplet.Navigate.back() isn't triggered twice when closing overlays

---

js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/6114
Follows https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/334

Updates flFilter parsing to match new data flow

---

js/layout-javascript/small-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5817 https://github.com/Fliplet/fliplet-studio/issues/6119
Follows #334

Refactors "My profile" feature to match the new data flow

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/6121

Leave bookmark toggle as it is when closing filter overlay

---

css/interface.css
js/interface.js
js/interface.templates.js
templates/interface/detail-view-panels.interface.hbs

Ref. https://github.com/Fliplet/fliplet-studio/issues/6126

Adds sortable functionality to detail view fields

---

js/layout-javascript/small-h-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5817
Follows #334

Fixes an issue where deep linking to an entry wasn't working

---

css/build.css

Ref. https://github.com/Fliplet/fliplet-studio/issues/5817
Follows #334

Ensures edit and delete button styles are consistent

---

js/layout-javascript/agenda-code.js
js/layout-javascript/small-h-card-code.js

Follows #334 
- Fixes an issue where agenda items are not separated by dates https://github.com/Fliplet/fliplet-studio/issues/6120
- Fixes issues with the auto-updating detail view https://github.com/Fliplet/fliplet-studio/issues/6127

Fixes QA issues

---

css/layout-css/agenda-style.upload.css
css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css

Ref. https://github.com/Fliplet/fliplet-studio/issues/6145

Fixes an issue where filter options in the overlay were hidden for the Simple List layout

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/6146

Adds hooks for monitoring search input changes

---

js/interface-lists.js

https://github.com/Fliplet/fliplet-studio/issues/5648
Id can be also letters.  

Ensures data view settings save correctly after changing image fields

---

css/layout-css/agenda-style.upload.css

Fliplet/fliplet-studio#5710
Position fixed does not seem to work in IE in this case. I changed to position relative.

Agenda layout looks correctly on IE

---

css/interface.css
vendor/select2.css

https://github.com/Fliplet/fliplet-studio/issues/6219

Ensures data source dropdown is always fully visible in Studio

---

css/layout-css/agenda-style.upload.css
css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css
css/layout-css/small-h-card-style.upload.css

Ref. https://github.com/Fliplet/fliplet-studio/issues/6205
This ensures that the content in LFD detail view is breaking long words.

Forces extra wide content to break into multi lines in detail overlay

---

js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/6297

Fixes an issue where HTML entities and tags were affecting search results

---

css/layout-css/agenda-style.upload.css
css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css
css/layout-css/small-h-card-style.upload.css
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

https://github.com/Fliplet/fliplet-studio/issues/5635
Long text in the news feed title will be clamped by 3 lines

Long text in the news feed title will be clamped by 3 lines

---

widget.json

Ref. https://github.com/Fliplet/fliplet-studio/issues/4389

[Maintenance] Removes beta tag

---

css/layout-css/agenda-style.upload.css
css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css

https://github.com/Fliplet/fliplet-studio/issues/5819
The close icon on a search value is centered with a text
Chrome
Edge
Firefox
IE11

The close icon on a search value is centered with a text

---

js/interface-lists.js

https://github.com/Fliplet/fliplet-studio/issues/5884
If a user will not select the 'Username data field(s)' error will be shown correctly
https://share.getcloudapp.com/yAu2XG7R

If a user will not select the 'Username data field(s)' error will be shown correctly

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

https://github.com/Fliplet/fliplet-studio/issues/6186
Changed hidden class assignment.
https://streamable.com/39eya5

Limit text now is hidden when user is searching or filtering

---

js/interface-lists.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/6376

[Fix] Ensures entry management screens can be selected

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Reverts Fliplet/fliplet-widget-dynamic-lists#363

Revert "Limit text now is hidden when user is searching or filtering"

---

css/layout-css/news-feed-style.upload.css

https://github.com/Fliplet/fliplet-studio/issues/5890
Removed CSS according to Tony's comment.

Fixes an issue where news feed details don't match the body font size

---

widget.json

https://github.com/Fliplet/fliplet-studio/issues/6417
Added layout attribute according to Hugo's comment.

[Fix] Added layout attribute 

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/6509

[Feat] Allows data source passport data to extend SAML2 passport data

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

Issue ref: https://github.com/Fliplet/fliplet-studio/issues/6466
- Added `Fliplet.Widget.updateHighlightDimensions()`

[Feature] Get correct highlight size

---

js/layout-javascript/agenda-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/6763

[Fix] Fixes an issue on touch device where agenda dates are incorrectly selected

---

css/build.css

Reverts Fliplet/fliplet-widget-dynamic-lists#395

Revert "[Fix] LFD widget is now aligned on all screens."

---

css/layout-css/agenda-style.upload.css
css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css

Reverts Fliplet/fliplet-widget-dynamic-lists#394

Revert "[Fix] Removed icon opacity for appearence settings to work correctly "

---

js/layout-javascript/agenda-code.js

https://github.com/Fliplet/fliplet-studio/issues/6814
Show agenda filters.
https://share.getcloudapp.com/wbuW2Gg1

[Fix] Show agenda filters.

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

https://github.com/Fliplet/fliplet-studio/issues/6814
Show filters in overlay
https://share.getcloudapp.com/WnuJeALn

[Fix] Show filters in overlay

---

css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css

Ref. https://github.com/Fliplet/fliplet-studio/issues/6899
Follows #410

[Fix] Reverts to using 4.4em for line-clamped container height

---

css/layout-css/news-feed-style.upload.css

Ref. https://github.com/Fliplet/fliplet-studio/issues/6899
Follows #410

[Fix] Tweaks max-height for news feed summary

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/query-parser.js
js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/6997

[Fix] Ensure filters remain accessible even if filter query is incorrect or incorrectly parsed

---

js/utils.js

Ref. ["dynamicListFilterColumn" LFD query selects all same values from all columns when specifying it to select a certain value from a certain column ](https://weboo.atlassian.net/browse/ID-29)

[Fix] Ensures query parameters only selects filter values matching the provided column names

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/utils.js

https://weboo.atlassian.net/browse/OD-18?atlOrigin=eyJpIjoiYmY0ZDUzNzFlZTY4NDU0ZDgwNjdiMTYyMzc3NmEzMjkiLCJwIjoiaiJ9
Show the add button at 20 px right from the LFD item list.
https://share.getcloudapp.com/mXuybWxO

[Fix] Show add button at 20 px right from the LFD item list.

---

js/layout-javascript/agenda-code.js

https://weboo.atlassian.net/browse/OD-62
Fixed bookmarks behaviors.
https://share.getcloudapp.com/lluYpgYD

[Fix] Fixes and issue with agenda bookmark filtering not working

---

js/layout-javascript/agenda-code.js

https://weboo.atlassian.net/browse/OD-63
Fixed filters behaviors.
https://share.getcloudapp.com/6que4N88

[Fix] Fixes and issue with agenda filters not working

---

js/layout-javascript/simple-list-code.js

https://weboo.atlassian.net/browse/OD-79
Fixed simple list item opening
https://share.getcloudapp.com/z8uZelW7

[Fix] Fixed simple list item opening

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

OD-80
https://weboo.atlassian.net/jira/software/projects/OD/boards/9?selectedIssue=OD-80
fix LFD bugs for Simple List and News Feed
https://screencast-o-matic.com/watch/cYQ0lidoZE

OD-80 [BUG] Filters are not available for all LFD

---

js/interface.js

https://weboo.atlassian.net/browse/OD-115
Data sources that were created in the old data source provider will appear in the new data source provider.
https://share.getcloudapp.com/rRuodP5l

OD-115 [Fix] Data sources that were created in the old data source provider will appear in the new data source provider.

---

js/interface.js

OD-294 https://weboo.atlassian.net/browse/OD-294
Save field names after clicking 'Back to settings' in Data view settings
https://screencast-o-matic.com/watch/cYlb2F8vA9

OD-294 [Fix] Save field names after clicking 'Back to settings'

---

js/interface.js

OD-293 https://weboo.atlassian.net/browse/OD-293
After clicking on `Configure security rules' security rules are not added when feature that requires them are disabled
https://screencast-o-matic.com/watch/cYlr638pbi

OD-293 [Fix] Add only required security rules

---

js/interface-lists.js
js/interface.js

OD-295 https://weboo.atlassian.net/browse/OD-295
Make Data source not disappearing after failed form validation with required fields
https://screencast-o-matic.com/watch/cYlb2w8vpE

OD-295 [Fix] Make Data source not disappearing after failed form validation

---

css/layout-css/agenda-style.upload.css
css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css

OD-297 https://weboo.atlassian.net/browse/OD-297
Filter overlay now is not hidden when the LFD is under an Accordion.
https://screencast-o-matic.com/watch/cYlbo48vWd

OD-297 [Fix] Overlay filter's height

---

js/interface.js

OD-294 https://weboo.atlassian.net/browse/OD-294
Show selected None and Custom security rule after clicking 'Back to Settings'
https://screencast-o-matic.com/watch/cYlr6a8pFJ

OD-294 [Fix] Show selected None and Custom security rule after clicking 'Back to Settings'

---

js/utils.js

OD-311 https://weboo.atlassian.net/browse/OD-311
OD-316 https://weboo.atlassian.net/browse/OD-316
Don't apply sorting if there are no records in search or bookmark list.
https://monosnap.com/file/k2GTUU3nOVRav3FPM51uxKksOKDzXW

OD-311 OD-316 [Fix] Don't sort if records are empty

---

interface.html

Requires https://github.com/Fliplet/fliplet-api/pull/4461

ID-576 [Fix] Remove sortable class so the provider is opened via POST

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js
js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-577

ID-577 [Fix] Append data source entry ID to existing queries when editing entries

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

Ref. https://weboo.atlassian.net/browse/ID-577
Follows https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/495

ID-577 [Fix] Append data source entry ID to existing queries when adding entries

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-577

ID-577 [Fix] Fixes an error when query strings are undefined

---

js/interface.js

OD-324 https://weboo.atlassian.net/browse/OD-324
Set Equals as default instead of 'none'
https://monosnap.com/file/xfYMK5XXVCBy1ubSNjaK8mbDD37NRz

OD-324 [Fix] Set Equals as default instead of 'none'

---

js/interface.js

OD-324 https://weboo.atlassian.net/browse/OD-324
Set Enter Value as default value type
https://monosnap.com/file/HvXJDrQmMSMvhgsOenRzu6WOgNgYio

OD-324 [Fix] Set Enter Value as default value type

---

interface.html

OD-376 https://weboo.atlassian.net/browse/OD-376
Updated need help link for LFD app personalisation feature
https://monosnap.com/file/cPU69cUIei6YFv3B9YhG0zHRU3Cu4y
@upplabs-alex-levchenko @AndrRyaz @YaroslavOvdii

OD-376 [Feature] Updated need help link for LFD app personalisation feature

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

Reverts Fliplet/fliplet-widget-dynamic-lists#564

Revert "OD-478 [Fix] Prevent hiding LFD if beforeOpen hook was rejected"

---

js/interface.js

@sofiiakvasnevska @inna-bieshulia
OD-539 https://weboo.atlassian.net/browse/OD-539
The component loading is fixed when DataSource is in trash
https://storyxpress.co/video/kqw26g55oni5zutas

OD-539 [FIX] Fix - settings aren't loaded

---

css/interface.css
js/layout-javascript/small-h-card-code.js

@sofiiakvasnevska @inna-bieshulia
OD-492 https://weboo.atlassian.net/browse/OD-492
Added title 'Email field', fixed transition to chat
https://storyxpress.co/video/kqjj5ius2kawddgf5
https://storyxpress.co/video/kqjj6xuwt2iqxka73
@upplabs-alex-levchenko @S-Volodymyr

OD-492 [Fix] Create chat settings for the LFD directory & featured list layout

---

js/layout-javascript/agenda-code.js

Ref. https://weboo.atlassian.net/browse/ID-1371

ID-1371 [Fix] Ensure agenda session title is correctly passed to surveys/polls/questions

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

Ref. https://weboo.atlassian.net/browse/ID-1432

ID-1432 [Fix] Ensure LFD is in the correct state when refreshing after comments are opened and closed

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

Ref. https://weboo.atlassian.net/browse/ID-1444

ID-1444 [Fix] Use the correct selector for finding opened entry ID

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-1373

ID-1373 [Feat] Add support for date range filter queries

---

js/interface.js

OD-566 https://weboo.atlassian.net/browse/OD-566
**Problem:** Control which supposed to reflect validation lays inside of the iframe and does not fall into current selection.
**Solution:** Added emit for transmission to the provider and further processing within the provider.
Reviewers

OD-566 [Fix] Ensures "User data" field is required and highlighted if it is empty

---

interface.html

Ref. https://weboo.atlassian.net/browse/ID-1522

ID-1522 [Fix] Fixes an issue where filter template couldn't be reset

---

interface.html
js/interface.js

Ref. https://weboo.atlassian.net/browse/ID-1523

ID-1523 [Feat] Show a confirmation dialog when template reset is complete

---

css/build.css

Ref. https://weboo.atlassian.net/browse/ID-1487

ID-1487 [Fix] Fixes IE 11 filter layout issue

---

css/build.css

Ref. https://weboo.atlassian.net/browse/ID-1487

ID-1487 [Fix] Fixes IE 11 layout issues for date filter in overlay

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

Ref. https://weboo.atlassian.net/browse/ID-1473

ID-1473 [Feat] Wait for entry to open before rendering list

---

css/build.css

Ref. https://weboo.atlassian.net/browse/ID-1529
Requires https://github.com/Fliplet/fliplet-api/pull/4973

ID-1529 [Fix] Tweaks date filter icon dimensions

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-1643
Follows https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/636

ID-1643 [Fix] Ensures non-text fields are correctly localised when it's also used as a filter

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-1681
Follows https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/636

ID-1681 [Fix] Leave HTML summary fields unescaped

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-1688
Follows https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/636

ID-1688 [Fix] Ensures null or undefined values are displayed as empty string

---

js/interface.js

Ref. https://weboo.atlassian.net/browse/ID-1718

ID-1718 [Fix] Prevent error when data source isn't assigned

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-1778

ID-1778 [Fix] Clear number filters when all filters are cleared

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-1796

ID-1796 [Fix] Ensures filters are correctly reset after using multiple filters

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js
js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-1804

ID-1804 [Fix] Avoid splitting filter values by comma if it's a date/number filter

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-1816

ID-1816 [Fix] Tweaks filter range validation for different types

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-1823

ID-1823 [Fix] Improve number parsing and caching for filter comparison

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-1824

ID-1824 [Fix] Include arrays and data from checkboxes for date & number filters

---

js/layout-javascript/small-card-code.js

Ref. https://weboo.atlassian.net/browse/ID-1841

ID-1841 [Fix] Avoid the opening glitch when detail view opening is delayed

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-1956

ID-1956 [Fix] Check for arrays when assess admin users

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-2083

ID-2083 [Fix] Ensures "Date is now" filter works correctly

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js
js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-2088

ID-2088 [Fix] Ensures prefilters work if LFD custom code was enabled

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-2088
Follows https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/681

ID-2088 [Fix] Updates apiQueryData assessment to include legacy layout code

---

css/build.css

Ref. https://weboo.atlassian.net/browse/ID-1875

ID-1875 [Fix] Fix number filter height

---

css/interface.css
js/interface.js

@romanyosyfiv
OD-631 https://weboo.atlassian.net/browse/OD-631
**Problem**: The content was not updated because the tabs were hidden
**Solution**: When resetting by default, tabs are given an "invisible" class that hides them using a height style
https://user-images.githubusercontent.com/86256215/164671541-7ada0423-5491-4b40-8d0d-c289d39802a8.mp4

OD-631 [Fix] Fixes a problem where custom HTML code is not saved correctly after resetting

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-2210

ID-2210 [Fix] Correctly assign session data as filter values

---

js/layout-javascript/agenda-code.js

Ref. https://weboo.atlassian.net/browse/ID-2364

ID-2364 [Fix] Fixes an issue where Agenda detail view can't open images

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

Dynamic List -> LFD -> Social Comment count
This PR has fixed the incorrect comment count on adding and removing comments. 
[XOR-416](https://weboo.atlassian.net/browse/XOR-416)
[XOR-417](https://weboo.atlassian.net/browse/XOR-417)
https://user-images.githubusercontent.com/101858104/188581667-a7f87524-b512-4983-bfeb-af8a47a3c6e3.mp4
None
None
None

XOR-416 [FIX] Ensure social comments display correct comment count

---

js/layout-javascript/agenda-code.js

Delete session from agenda LFD
This PR has added checks and UI updates when a session is getting deleted from agendas. 
[XOR-428](https://weboo.atlassian.net/browse/XOR-488)
Relevant sample input/output screen recordings.
https://user-images.githubusercontent.com/101858104/191012844-ea6c74ca-5c16-46a5-8616-1f17acfa44be.mp4

XOR-488 [FIX] Ensure Agenda updates accordance to delete session functionality

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Ref. https://weboo.atlassian.net/browse/ID-2601

ID-2601 [Feat] Sanitize search value before displaying

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-2599

ID-2599 [Feat] Sanitize HTML in comments before display

---

js/layout-javascript/agenda-code.js

Ref. https://weboo.atlassian.net/browse/ID-2698

ID-2698 [Fix] Keep the scroll position when activating filters

---

css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Ref. https://weboo.atlassian.net/browse/ID-2658

ID-2658 [Fix] Only change z-index for the instance container with active filter overlay

---

js/query-parser.js
js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-2819

ID-2819 [Fix] Prevent dynamicListFilterHideControls query parameter from stopping the list from loading

---

js/query-parser.js
js/utils.js

* [ID-2819 [Fix] Prevent dynamicListFilterHideControls query parameter from stopping the list from loading https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/711
* ID-2818 [Fix] Parse filter values into suitable types https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/712

Release to Production

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-2861

ID-2861 [Fix] Improve performance of auto-populated detail views

---

js/interface.js

Ref. https://weboo.atlassian.net/browse/ID-2895

ID-2895 [Fix] Prevent errors with code editors when custom code is undefined

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

Ref. https://weboo.atlassian.net/browse/ID-3061

ID-3061 [Feat] Allow developers to customise query when getting comment user list

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-3041

ID-3041 [Fix] Strip HTML tags from search values

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-3041

ID-3041 [Fix] Replace line breaks when performing searches

---

js/utils.js

Reverts Fliplet/fliplet-widget-dynamic-lists#731

Revert "release 20240131"

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Reverts Fliplet/fliplet-widget-dynamic-lists#734
due to QA failed

Revert "ID-4143 [fix] LFD data view settings reordering fields file"

---

js/layout-javascript/agenda-code.js

LFD - Agenda Screen
Centers the selected agenda element on all screen sizes. 
[PS-1118](https://weboo.atlassian.net/browse/PS-1118)
[PS-1118]: https://weboo.atlassian.net/browse/PS-1118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PS-1118 [FIX] center selected element on desktop screens
