js/layout-javascript/feed-comments-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

To ensure images are correctly rendered for encrypted files, this adds authentication tokens to image URLs before they are used for templating.
Ref. https://github.com/Fliplet/fliplet-studio/issues/2877

Authenticate image URLs before using data for templating

---

css/layout-css/agenda-style.upload.css

Fixes the following problem
If there are LFD instances where custom CSS has been activated, use the following custom CSS to fix the issue:
```css
.new-agenda-list-container .agenda-list-day-holder {
vertical-align: top;
}
```

Ensures lists across agenda dates are aligned to the top

---

css/layout-css/small-card-style.upload.css
css/layout-css/small-h-card-style.upload.css
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

Issue reference: https://github.com/Fliplet/fliplet-studio/issues/3436
Now there's always a bit of content above the fold.

Fixes image size

---

js/interface.js

Reference of issue: https://github.com/Fliplet/fliplet-studio/issues/3439
An alert will be shown when a user saves or closes a data table overlay. The alert will notify users that if they changed column names, they have to confirm they still have the right fields selected.

Alert modal after closing data overlay

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

tl;dr https://www.useloom.com/share/cf12d0da214a4237830884b4bbbef5d8
Based on the discussion and ideas shared in https://github.com/Fliplet/fliplet-studio/issues/3582 I added some optimisations to the LFD so now it should load faster.
The largest performance hit we took was basically in a couple of quadratic complexity nested loops which were unneeded.
The next step to optimise was to reduce 2 unneeded sort/orderBy statements to one.
The final step was to introduce incremental rendering via [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame). In short, we batch all the records by 100s (configurable at code level) and render those batches to the screen whenever the browser gives us the opportunity to do so.
What that means is that we leave …

Added optimizations to layouts.

---

js/default-configs/layouts-config.js

This adds a new default sort condition to the Agenda style.
Making it so that it sorts by date first and then by time.
Reference of explanation why: https://github.com/Fliplet/fliplet-e2e-tests/issues/249

Added a second sort condition by default - Agenda

---

build.html
js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js
js/query-parser.js
widget.json

This PR adds a query parser to all LFD layouts.
I've followed a similar naming convention to the one for Storage.
These are some examples of queries which will work the same way as if they were applied through PV (i.e Storage):
`dynamicListOpenId=1128` - opens a specific entry
`dynamicListSearchColumn=Name&dynamicListSearchValue=Angel` - will search for `Angel` in the column `Name`
`dynamicListFilterValue=Angel,28` - will select the filter options `Angel` and `28`
`dynamicListFilterValue=Angel,28&dynamicListFilterHideControls=true` - will select the filter options `Angel` and `28` **and will also hide the controls**
`dynamicListPrefilterColumn=Name&dynamicListPrefilterValue=Angel&dynamicListPrefilterLogic=contains` - will pre-filter the list, by testing if any `Name` `contains` `Angel` …

Added a query parser to LFD

---

css/layout-css/news-feed-style.upload.css

Ref. https://github.com/Fliplet/fliplet-studio/issues/3853

Ensure overflows are hidden in Webkit (iOS & Safari) for the news feed layout

---

css/layout-css/small-card-style.upload.css

Issue ref: https://github.com/Fliplet/fliplet-studio/issues/3995#issuecomment-470911723
Fixes bookmark position for tablet and above.

Fixes bookmark position for tablet and above

---

css/layout-css/small-card-style.upload.css
js/layout-javascript/small-card-code.js

- With this PR we now have a `.opening` and `.closing` classes added to the list item element, to be used in the CSS to control how elements react during the animation.
- We used the `.opening` class to restore the expand animation that was "broken" after a change that fixes round corners from disappearing on specific devices.

Fix to the expand animation of small cards

---

js/layout-javascript/small-card-code.js

After a closer look at how the expand works now (compared to the initial versions of the LFD) I noticed that we actually do not require the position of the body at all, because we know that the overlay that will fade in after the expand animation is always filling the screen on mobile.
This change won't affect the Tablet and Desktop animations/overlay.
https://cl.ly/df2c5785e680

Removed use of unnecessary use of body position

---

js/layout-javascript/small-card-code.js

We use the value of the top margin to figure out the top offset for the expand animation, and because the HTML tag has a `margin-top` with `env(safe-area-inset-top)` we can also use this value for phones with notches.

Fix for phones with notch

---

css/layout-css/news-feed-style.upload.css
js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

- Adds new `flListDataAfterGetData` hook where `data.records` contains records that can be manipulated.
- Tweaks news feed card styles to ensure rounded corners are clipped in Safari and iOS apps.
- Tweaks filter parsing to allow `null` attributes.

Changes for LFD to support building podcast app

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

This includes:
1. [x] Getting user session via `Fliplet.Session.get()` is updated to use `Fliplet.User.getCachedSession()`
1. [x] Getting the most recent list of data source columns is updated to only when `detailViewAutoUpdate` is enabled
1. [x] Getting the most recent list of data source columns is updated to use a collation of all data source entries.
Other API changes that would also speed up the LFD:
1. `Fliplet.Media.Folders.get()` updated to use cached response and increase load speed (https://github.com/Fliplet/fliplet-api/pull/3290)
1. Use offline resource where possible when using `Fliplet.Content` or `Fliplet.Profile.Content`, speeding up loading and processing time for bookmarks. (https://github.com/Fliplet/fliplet-api/pull/3289)

Ensures offline resources are used for all layouts

---

js/utils.js

Improves parser to exclude timezone depending on date format
Ref. https://github.com/Fliplet/fliplet-studio/issues/4030 and https://github.com/Fliplet/fliplet-studio/issues/3835
- Parses date using just the date string if it starts with the ISO date format
- Only converts moment to UTC time if the date string starts with the ISO date format
This ensures the recommended input format always works, and any other format is issued a warning before letting `Date` and `moment` parse its value.

Improves parser to ensure Agenda dates are correct

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Requires https://github.com/Fliplet/fliplet-api/pull/3322
@squallstar https://github.com/Fliplet/fliplet-api/pull/3322 reverted the default back to retrieving all data when reading like/bookmark status & counts. Options have been added here when creating the like button so that in the case of bookmarking LFD can retrieve entries specific to the user.
Ideally though, it would be better to be able to only retrieve a count number instead of reading all the entries and then doing a count on the client side.

Limit bookmarking like queries to only user entries

---

js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4208
Special characters are removed from search term
Special characters are removed from records for comparison

Ignore special characters when performing searches

---

js/utils.js

Prevents the LFD from not loading when an invalid image URL is used

Corrects record referencing when invalid image URLs are used

---

css/layout-css/small-card-style.upload.css

Ref. https://github.com/Fliplet/fliplet-studio/issues/4512#issuecomment-501676513

Add border radius on the left when no images are used in the small card layout

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js
js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4528
Computed properties will overwrite any existing properties. When this happens, a warning message will be shown to the user in developer console.
```
Computed field(s) "Foo, Bar" are already defined as a property for one or more records. All computed fields will overwrite existing properties. Use a different computed field name if you want to prevent the data from being overwritten.
```

Add support for computed fields

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js
js/query-parser.js
js/utils.js

Merging into `feat/filter-rebuild` for https://github.com/Fliplet/fliplet-studio/issues/4343
Ref. https://github.com/Fliplet/fliplet-studio/issues/4342 https://github.com/Fliplet/fliplet-studio/issues/4550
https://github.com/Fliplet/fliplet-cli/pull/108
```
dynamicListFilterColumn=Tags,Category&dynamicListFilterValue=[Foo,Buzz],Enterprise%20software
```
The queries above specify:
```js
(Tags.includes("Foo") && Tags.includes("Buzz") && Category === 'Enterprise')
```

Add support for specifying columns in filter queries

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/3263
This implementation needs to be updated after `Fliplet.Page.Context.push()` and `.pull()` are added to prevent the navstack from being overwritten.

Initial support for returning users to previously opened entries

---

js/interface-lists.js
js/interface.js

When clicking on the Save & Close button before all data is loaded, the component is saving empty data. 
Added variable _this.isLoaded which is false by default, and its value changes to true when data is loaded. Added check to Fliplet.Widget.onSaveRequest which is allowing to save component only when data is loaded.
ref https://github.com/Fliplet/fliplet-studio/issues/4370

Prevent configuration loss if the interface is saved before everything has loaded

---

css/layout-css/agenda-style.upload.css

The bookmark div is displayed even if the bookmark feature is disabled.
Changed default state of the bookmark div to display none, and added the new CSS rule which giving display flex when this feature is enabled.
ref https://github.com/Fliplet/fliplet-studio/issues/4291

Disabling bookmark leaves a blank space

---

css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

The issue was that the horizontal scroll bar was overlapping filters items when there are many filters value in one column.
Changed filter animation that used to be there. It used to calculate dynamically filter block height, but in Safari on the first time opening the height calculated incorrectly. Now it isn't calculating a filter block height but making it 100%. This is what helped to display it right in Safari.
ref https://github.com/Fliplet/fliplet-studio/issues/4713

Horizontal scroll bar overlaps filters items 

---

css/layout-css/small-card-style.upload.css

The issue was that content was going beyond the card when it is too long.
Added overflow hidden property for small-card.
ref https://github.com/Fliplet/fliplet-studio/issues/4229

Content goes beyond the card when it is too long

---

css/layout-css/small-card-style.upload.css

The issue was that the bookmark icon on tablets and desktop was aligned to the right.  
Now on all devices, bookmark aligned to the left.
ref https://github.com/Fliplet/fliplet-studio/issues/4123.

Bookmark - Not at the right position

---

css/layout-css/small-card-style.upload.css

Fixed padding issue occurred in PR https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/202.
Width of Directory LFD returned to normal.
ref https://github.com/Fliplet/fliplet-studio/issues/4229.

Overflow bug fix 

---

.gitignore
css/layout-css/small-card-style.upload.css

Vertical aligned close icon.

---

css/layout-css/agenda-style.upload.css

https://github.com/Fliplet/fliplet-studio/issues/4867
Change z-index for agenda LFD layout, so it's didn't overlaps the menu bar in IE 11.
Done the same thing for the bookmark button, which overlaps the menu bar.
IE 11.1.18362.0
Edge 18.18362
Chrome 76.0.3809.100

Fixed agenda layout so it doesn't overlap the menu bar now in IE 11.

---

js/interface.js

https://github.com/Fliplet/fliplet-studio/issues/4953
Removed extra tag from filter and search

Prevents extra tag being added when configuring filter and search 

---

js/interface.js

https://github.com/Fliplet/fliplet-studio/issues/4953
Removed ability to create custom tags in filter and search fields

Removed ability to create custom tags in filter and search fields

---

css/build.css
css/layout-css/small-card-style.upload.css

Aligned close icons for native devices. 

Aligned close icons for native devices. 

---

css/build.css

Added different padding's to Android and iOS devices
iOS 12
Android 9

Added different padding's to Android and iOS native devices

---

js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5012

Stop removing image URLs when they don't match HTTP URL or Base 64 patterns

---

js/default-table-data/layouts-table-config.js

Added missing Linkedin select in layouts config.
Fliplet/fliplet-studio#5020

Linkedin field in featured list layout now has default value

---

js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5115
Use the following code to revert back to the old filter match type:
```js
Fliplet.Hooks.on('flListDataBeforeGetData', function (options) {
_.set(options, 'config.filterMatch', 'all');
});
```

Make filter match type configurable

---

css/build.css

Fixed icon position for iOS devices

Fixed icon position for iOS devices

---

js/layout-javascript/news-feed-code.js

Fliplet/fliplet-studio#5085
Apparently this piece of code was not added as it was in a simple-list layout. This caused entryComments to be undefined. Now works as expected.

User is now able to edit messages in News Feed layout

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

Fliplet/fliplet-studio#5086
Corrected variable name. Updated confirm to fliplet.modal.confirm.

Deleted comment is now removed from UI right after deleting

---

css/build.css

@tonytlwu @squallstar @sofiiakvasnevska 
Aligned close icon for Firefox, Edge and Android 9 Chrome.
Android 9 Chrome
MS Edge
Firefox

Aligned close icon for Firefox, Edge and Android 9 Chrome

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

1. Developers can use the snippet below to assess what triggered the open event.
```js
Fliplet.Hooks.on('flListDataBeforeGetData', function (options) {
options.config.beforeOpen = function (data) {
// data.event contains the event that triggered the opening
};
});
```
2. Users can set a query parameter when opening an entry via query to ensure users return to the previous page when closing the detail view
```
dynamicListOpenId=<id>&dynamicListPreviousScreen=true
```

Adds event to beforeOpen hook and support for navigating back via query

---

js/default-configs/layouts-config.js

Fliplet/fliplet-studio#4969
Added image data-field in image layouts.
Image Data Field now has Field label "No label" compared to others "Column name as label". Should we do anything about it?

Image data field now has field type set as image

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

Fliplet/fliplet-studio#5085
The bug occurred because editing comments was updating the last comment. Now it updates comment by id.

Edited comments now updated according to its ID

---

css/layout-css/agenda-style.upload.css

Fliplet/fliplet-studio#5238
Added fixed width to the agenda-item-content-holder.

Long words now not going beyond the edge of the screen

---

js/build.js
vendor/clamp.js
widget.json

https://github.com/Fliplet/fliplet-studio/issues/5030
Show clipped description in a simple list for IE11
MS IE11
MS EDGE
Firefox
Chrome
Use set interval function to wait until the element will appear in the DOM.

Show clipped description in simple list for IE11

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

Fliplet/fliplet-studio#5084
Added filter to left out empty comments.

Empty comments (or only spaces) will be filtered and not get rendered to UI

---

js/interface-lists.js

https://github.com/Fliplet/fliplet-studio/issues/5312
Now when user is changing data field select value, field id will be removed or added back.

Saving data view settings now works correctly

---

js/interface.js

https://github.com/Fliplet/fliplet-studio/issues/5312
When user deletes field, id is removed from the array.

Fixed saving data view settings

---

css/build.css

https://github.com/Fliplet/fliplet-studio/issues/5347
Returned CSS code to support fa-times-thin class for the close icon according to this [comment](https://github.com/Fliplet/fliplet-studio/issues/5347#issuecomment-558279446).
I wasn't able to test it properly because of cant replicate the issue.

Returned CSS code to support fa-times-thin class for close icon

---

js/interface-lists.js

https://github.com/Fliplet/fliplet-studio/issues/5439
Highlight errors in the directory layout

Highlight errors in the directory layout

---

js/interface-lists.js

https://github.com/Fliplet/fliplet-studio/issues/5439#issuecomment-572021605
Fixed error highlight when deleting entry set to the users and admins

Fixed error highlight when deleting entry set to the users and admins

---

js/utils.js

https://github.com/Fliplet/fliplet-studio/issues/5447
Before the issue occurred because of indexOf check. 
Now we will find the last dot in the image name, remove ext  and then compare names.

Now images with similar titles display correctly

---

js/interface.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5131
A `setupLayoutSelector()` function is created to set up the layout selector, which only does anything if a layout isn't already selected. This is previously being executed (and layout selector added to the DOM) even if the UI never gets used. This loads 28.4MBs of GIF into the browser and slows down the overall time to render.
Locally, this has reduced the time to render from ~8.5s to ~4.5s.
On staging, the time to render is currently ~3s.
On production, the time to render is currently ~7s.

Speed up interface load time if a layout is already selected

---

js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4257
By having a `Query` field with values such as `foo=bar`, users can use the following code to attach a query value when linking an LFD entry to a screen.
```js
Fliplet.Hooks.on('flListDataBeforeGetData', function (options) {
if (options.config.summaryLinkAction) {
options.config.summaryLinkAction.queryColumn = 'Query';
}
});
```
[Computed fields](https://developers.fliplet.com/API/components/list-from-data-source.html#configurations) can also be used to generate the query column.

Adds query support when configuring an item to link to a screen

---

css/layout-css/agenda-style.upload.css
js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/utils.js

Also follows https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/299 to adjust some agenda layout spacing.
To define a custom primary key:
```js
Fliplet.Hooks.on('flListDataBeforeGetData', function (options) {
options.config.dataPrimaryKey = 'Session ID';
});
```
To create a custom primary key based on various data:
```js
Fliplet.Hooks.on('flListDataBeforeGetData', function (options) {
options.config.dataPrimaryKey = function (data) {
return _.get(data, 'record.data.Title') + '-' + _.get(data, 'record.data.Date');
};
});
```

Adds method for customising primary key and entry identifiers for social features

---

js/query-parser.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5850
By using `this.Utils.String.splitByCommas()`, the function is able to detec the presence of `" "` quotes, which ignores the commas as delimiters.

Adds support for splitting query values with commas

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

- Fixes an issue where bookmarks are initialised multiple times (ref. https://github.com/Fliplet/fliplet-studio/issues/5861)
- Adds `config.forcenRenderList` as an option to force every list item to render instead of simply removing existing entries
- Adds `options.initialRender` as a parameter in `flListDataAfterRenderList` hooks to signify whether the hook is fired from an initial load or subsequent filters

Improves hooks for before and after list render

---

js/interface.js
js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
vendor/codemirror/addon/format/formatting.js
widget.json

This PR adds support for
- creating a user's bookmarks view definition when creating the bookmarks data source (bundled by default)
- all internal features to use the above newly defined view
- adds new reference type for views
Existing usage will be unaffected as the bookmarks data sources won't have the view definition, resulting in simply skipping these inputs from having any effect.
---
requires https://github.com/Fliplet/fliplet-api/pull/3866

Support for segmentation user bookmarks

---

js/interface.js

https://github.com/Fliplet/fliplet-studio/issues/5394
Save a user data before reload after datasource closing
https://share.getcloudapp.com/v1urDkDj

Save a user data before reload after datasource closing

---

css/layout-css/agenda-style.upload.css
css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css
css/layout-css/small-h-card-style.upload.css

https://github.com/Fliplet/fliplet-studio/issues/5469
Added support CSS for the old version of the user templates
These styles are needed to add for the users with the old templates which doesn't have a `.close-icon` class on which we are targeting in the build.css. So to avoid this issue I've duplicated style from build.css to each layout CSS with their unique classes.

Added support CSS for the old version of the user templates

---

css/layout-css/small-card-style.upload.css

https://github.com/Fliplet/fliplet-studio/issues/5469#issuecomment-599418152
Removed the `.tablet` class from the CSS selector to ensure that we will apply styles for mobile devices as well.

Users with old templates will also see the close icon on the mobile devices

---

css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

https://github.com/Fliplet/fliplet-studio/issues/6062
Returned CSS code for old templates of the LFD so text would clamp properly

Returned CSS code for old templates of the LFD so text would clamp properly

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js
js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5817
- On initial data load, instead of preparing all summary view and detail view data, only add filter properties for adding filters onto the screen.
- When rendering the list view, only process records for the summary view data (skipping the detail view data processing).
- When opening an entry to show its details, add detail view data for the single record.
- Initial load
- Render time (see https://github.com/Fliplet/fliplet-studio/issues/5817#issuecomment-592224853 for detailed benchmarks)
- Opening an entry
- Filtering, search and bookmark filter
- Social features (bookmark, like, comment)
- Opening an entry on load (using the `dynamicListOpenId` parameter)
- Determining who has access to insert, edit and delete entries

Speeding up LFD load time

---

css/build.css
js/layout-javascript/simple-list-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5817
Follows #334 
Fixes an issue where the Simple List layout wasn't setting edit and delete permissions at all.
Fixes an issue where the delete button is sometimes full-width if the page contains other components, e.g. the form component.

Fixes QA issues due to refactoring for speed improvements

---

js/layout-javascript/agenda-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/6130
The `dataPrimaryKey` configuration was built to be used for bookmarking. This PR extends the feature to be used for polls, surveys and questions too. When going to the poll, survey and question screens, the `sessionId` query will be added to either send the data source entry ID or the primary key according to the `dataPrimaryKey` configuration.

Add customisable session ID queries to agenda links

---

js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/6145
The #334 PR mistakenly changed the assumed data structure for filter data in the `parseRecordFilters()` function in `utils.js`. This updates it so that it checks for both data structure formats.
Unfortunately, we can't simply revert the change since some LFD instances could have locked down the changes using custom JS.

Fixes a compatibility issue between versions of record processing code

---

css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/query-parser.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/4816
8 hooks related to comments have been added.
- `flListDataBeforeNewComment`
- `flListDataAfterNewComment`
- `flListDataAfterNewCommentShown`
- `flListDataBeforeUpdateComment`
- `flListDataAfterUpdateComment`
- `flListDataAfterUpdateCommentShown`
- `flListDataBeforeDeleteComment`
- `flListDataAfterDeleteComment`
2 query parameters are also added in relation to comments.
- **dynamicListOpenComments** (`true|false`) Open the comments view, if applicable (Default: `false`)
- **dynamicListCommentId** Open the comments view and scroll to the provided comment based on the comment ID

LFD hooks and query parameters for comments

---

css/layout-css/agenda-style.upload.css

https://github.com/Fliplet/fliplet-studio/issues/5713
Search button in the agenda will not go out the borders in the IE11
Button text set to white is because when I tested it I've changed the data-widget-package and CSS code doesn't apply.
When we merge it text color will be normal.

Search button in the agenda will not go out the borders in the IE11

---

css/layout-css/small-card-style.upload.css

https://github.com/Fliplet/fliplet-studio/issues/5601
The detail view will not open in edit mode
https://share.getcloudapp.com/Apur2dX4

Ensures detail view doesn't open in edit mode

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/6165
Adds data source ID and data source entry ID into comment settings for metadata processing.
`settings` is not used for identifying and retrieving comments, which means no functionality should be affected.

Start tracking data source and entry IDs in comments

---

css/layout-css/agenda-style.upload.css

https://github.com/Fliplet/fliplet-studio/issues/5710#issuecomment-611412999
Tony's comment in this issue.
Correct CSS to look correctly on IE.

Search container looks correct on IE

---

css/layout-css/agenda-style.upload.css

https://github.com/Fliplet/fliplet-studio/issues/5710
Somehow adding horizontal margin broke layout. Replaced with padding.
https://streamable.com/qkyo3f

Agenda search wrapper now looks correctly on IE on tablet and desktop

---

css/layout-css/agenda-style.upload.css

https://github.com/Fliplet/fliplet-studio/issues/5710#issuecomment-611412999
I have not realized that .fl-with-top-menu affects only default menu. This way it should work as expected. I tested with all menus.

IE agenda looks correct on all menu types

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/5481
Also adds `Email` as a fallback default for user email column as it's already used in the rest of the code (but not consistently).

Log session data when users are not able to comment

---

js/query-parser.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/6237
Query parameters are kept when user goes from Preview mode to Edit mode in Studio. This prevents the queries from being parsed and used as the component should remain in neutral of the queries in edit mode.

Don't parse queries in edit mode

---

js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/6318
Since this JS API change https://github.com/Fliplet/fliplet-api/pull/4032 the `Fliplet.Navigate.url()` self-determines whether the URL needs to be authenticated. There's therefore no need for the LFD to authenticate if it's passing the URL to `Fliplet.Navigate.url()`.
However, perhaps the fix should lie in the `Fliplet.Media.authenticate()` function so that the function never authenticates unless it's a native app? i.e. adding these 3 lines:

[Fix] Let Fliplet.Navigate.url() determine if authentication is needed

---

js/layout-javascript/agenda-code.js

https://github.com/Fliplet/fliplet-studio/issues/5868
Show filters when bookmarks are selected
https://share.getcloudapp.com/p9u7Rvy2
While I tested this solution no other bugs were noticed.

Show filters when bookmarks are selected

---

css/layout-css/agenda-style.upload.css
css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css
css/layout-css/small-h-card-style.upload.css
js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

https://github.com/Fliplet/fliplet-studio/issues/6067
The close icon on an old template on windows 7 will look normal with ie11

The close icon on an old template on windows 7 will look normal with ie11

---

css/layout-css/agenda-style.upload.css

https://github.com/Fliplet/fliplet-studio/issues/6150
Long filters will be cut with an ellipsis.

Long agenda filters will be cut with an ellipsis.

---

css/layout-css/agenda-style.upload.css
css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css
css/layout-css/small-h-card-style.upload.css

In this PR we are changing only `opacity` to `rgba` there is no visual changes happens.
These changes are needed for this [feature](https://github.com/Fliplet/fliplet-studio/issues/6225) to work right.

[Feature] Changed opacity to rgba so that component could change normally through new appearance settings. 

---

js/layout-javascript/agenda-code.js

https://github.com/Fliplet/fliplet-studio/issues/6224
Added cycle break before rendering no results HTML if there is no data.
https://streamable.com/v3qxnx

No results HTML will not appear if there is data found

---

css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

https://github.com/Fliplet/fliplet-studio/issues/6252
Similar logic is implemented in the agenda layout. 
When the user opens search/filter overlay, class "has-filter-overlay" is added to the body, and therefore z-index 1010 is applied (bottom-icon-bar-menu has 1009 z-index). When the user closes search/filter overlay using "back arrow" or by apply button,   class "has-filter-overlay"  is removed.

Bottom icon bar menu now is hidden when opening search/filter overlay

---

css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css

Fliplet/fliplet-studio#6150
Long filters will be cut with an ellipsis.

Long overlay filters will be cut with an ellipsis.

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

@sofiiakvasnevska @tonytlwu 
Fliplet/fliplet-studio#6186
Actually we can use the "truncated" variable. I was confused by it as it was reassigned in code and I did not see it. This way everything works as expected.

Limit text now is hidden when user is searching or filtering

---

css/layout-css/agenda-style.upload.css

https://github.com/Fliplet/fliplet-studio/issues/6223
The bookmark icon will be placed on the left as it should be.
https://share.getcloudapp.com/Apujmvnq
This issue occurred after this [PR](https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/373)

[Fix] The bookmark icon will be placed on the left as it should be.

---

js/layout-javascript/agenda-code.js

https://github.com/Fliplet/fliplet-studio/issues/6548
Show correct error message when the user doesn't have permissions to the Data Source.
Removed `.catch()` from `connectToDataSource()` function give controll over error handlers to the `initialize()` function.
It wouldn't have any effect on the current flow of the Agenda layout because the `connectToDataSource()` function used only with the `initialize()` function.

[Fix] Show correct error message when the user doesn't have permissions to the Data Source.

---

css/layout-css/agenda-style.upload.css
css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css

Fliplet/fliplet-studio#6225
As now we set icon opacity thought rgba we do not need extra opacity property.

[Fix] Removed icon opacity for appearence settings to work correctly 

---

css/build.css

https://github.com/Fliplet/fliplet-studio/issues/6620
LFD widget is now aligned on all screens
https://share.getcloudapp.com/8Lu7bkZj

[Fix] LFD widget is now aligned on all screens.

---

js/layout-javascript/agenda-code.js

https://github.com/Fliplet/fliplet-studio/issues/6763
Allow users to swipe agenda dates.
https://share.getcloudapp.com/5zuXq1bX
The issue was that the active slide index wasn't searched correctly.
For testing used the Android 9.0 simulator.

[Fix] Allow users to swipe agenda dates.

---

js/utils.js

Keep date format as `en` until localisation is properly rolled out
Required for https://github.com/Fliplet/fliplet-api/pull/4149

[Maintenance] Ensures date format doesn't change when date locales become available

---

css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/6899

[Fix] Line clamp text in IE 11 by setting max-height without using elllpses

---

css/build.css

https://github.com/Fliplet/fliplet-studio/issues/6858
Users will see filters text in overlay mode

[Fix] Users will see filters text in overlay mode

---

css/layout-css/agenda-style.upload.css
css/layout-css/news-feed-style.upload.css
css/layout-css/simple-list-style.upload.css
css/layout-css/small-card-style.upload.css

Fliplet/fliplet-studio#6225
As now we set icon opacity thought rgba we do not need extra opacity property.

[Fix] Removed icon opacity for appearence settings to work correctly

---

css/build.css

https://github.com/Fliplet/fliplet-studio/issues/6859
Filters won't go over the screen.
https://share.getcloudapp.com/2Nuy59O1

[Fix] Filters won't go over the screen.

---

js/query-parser.js
js/utils.js

Ref. https://github.com/Fliplet/fliplet-studio/issues/6997
This unifies all CSV parsing to one single function.
* Values are separated by `,`
* Values wrapped in `" "` are ignored
* Values wrapped in `[ ]` are parsed as nested arrays

[Fix] Ensures query parameters with nested arrays are correctly parsed.

---

js/layout-javascript/news-feed-code.js
widget.json

https://weboo.atlassian.net/jira/software/projects/OD/issues/OD-60?filter=myopenissues
Removed old alert from comment deletion

[Fix] Old alert appears when interacting with comments in LFD

---

js/layout-javascript/news-feed-code.js

https://weboo.atlassian.net/browse/OD-123
Removed news feed items hiding.
https://share.getcloudapp.com/yAulowgz

[Fix] OD-123 After comment overlay close items list wont disappear 

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-327
Users used to be able to set a filter query by merely specifying `dynamicListFilterValue`, but that was broken when https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/430 was implemented. This capability has been added back with a more reliable implementation to avoid https://weboo.atlassian.net/browse/ID-29 from happening again.

ID-327 [Fix] Fixes an issue where filters couldn't be selected using only query values

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

OD-102 https://weboo.atlassian.net/browse/OD-102
Stop propagation on `show.bs.collapse` to fix collapsing accordion (with nested LFD) when collapsing filters in overlay mode.
https://screencast-o-matic.com/watch/cYl2bP8oCX

OD-102 [Fix] LFD nested in Accordion OverlayFilter collapse

---

js/utils.js

OD-313 https://weboo.atlassian.net/browse/OD-313
There was a problem because `+undefined === NaN` but `+null === 0`
https://monosnap.com/file/uhyZBWYZZicxVXclkxzFj8WK1vrmOc

OD-313 [Fix] Fix sorting for numbers (null and zero)

---

js/utils.js

The following Handlebars helpers are removed as they will be [implemented via Fliplet's Handlebars library](https://github.com/Fliplet/fliplet-api/pull/4489), which must be deployed before the widget is deployed.
* `ifCond`
* `plaintext`
* `removeSpaces`

[Maintenance] Remove helpers defined in the Fliplet Handlebars library

---

js/layout-javascript/agenda-code.js

OD-457 https://weboo.atlassian.net/browse/OD-457
Show agenda cards after filter overlay hiding and after forward/backward animations
Overlay: https://monosnap.com/file/kZcO5e7Hya75p4UVJT649tFHkGOTHl
Animations: https://monosnap.com/file/m8wTwQFxppAHslVPhoVnsYr2ybOtwA
@upplabs-alex-levchenko @AndrRyaz @YaroslavOvdii

OD-457 [Fix] Show agenda cards after filter overlay hiding and after forward/backward animation

---

js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

OD-478 https://weboo.atlassian.net/browse/OD-478
Don't hide LFD if `beforeOpen` hook was rejected
https://monosnap.com/file/Jrg48lST68Q3l4BsbinKi5KdMqvVa3
@upplabs-alex-levchenko @AndrRyaz @YaroslavOvdii

OD-478 [Fix] Prevent hiding LFD if beforeOpen hook was rejected

---

.eslintrc
js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js
js/layout-javascript/small-h-card-code.js

Ref. https://weboo.atlassian.net/browse/ID-927
https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/562 modified the `showDetails()` function such that it no longer returned a promise, hence creating a problem with `showDetails().then()` when user returns to the LFD page to open an entry.

ID-927 [Fix] Ensure users can navigate back to an opened entry

---

js/layout-javascript/simple-list-code.js

OD-497 https://weboo.atlassian.net/browse/OD-497
Made comments overlay closeable in simle list LFD by fixing accessibility issue (no `event` parameter provided)
https://monosnap.com/file/OZrffKG0JzomX24qN5dTURTiJT7bsK

OD-497 [Fix] Make comments overlay closable in simple list

---

js/utils.js

https://weboo.atlassian.net/browse/OD-499
Added fallback when a file isn't a string but an object
https://share.getcloudapp.com/mXupL7Qb

OD-499 [Fix] Users will be able to open simple list detail view

---

js/layout-javascript/agenda-code.js

Ref. https://weboo.atlassian.net/browse/ID-1150
Possibly due to the number of date selectors, the rendering engine is unable to render the update styles based on the new classes.
This forces re-render by applying and removing CSS styles.

ID-1150 [Fix] Ensure date selectors are correctly highlighted

---

js/interface.js
js/layout-javascript/agenda-code.js
js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/utils.js
package-lock.json
package.json

Ref. https://weboo.atlassian.net/browse/OD-382 https://weboo.atlassian.net/browse/ID-1302
Following https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/592 I have updated the work to use and test drive our latest `Fliplet.Locale` JS API.
Also added:
- Localizing the numbers for like and comment counts, e.g. `1 234` for France and `1.234` for Italy or `1,234` for UK
Requires https://github.com/Fliplet/fliplet-api/pull/4805
**Agenda**
USA
Italy
Japan

OD-382 [Feature] Use locale format for displaying dates, times and numbers

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-1641
This brings the fix in https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/644 closer to the initial implementation in https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/149 while still allowing for number/date localisation.
Follows https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/636

ID-1641 [Fix] Only apply SafeString if custom templates are used

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-1750
The reported bug was caused by the `getImageUrlsByRegex()` function created in https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/562 checked the string for the `http://` prefix (and the alike). However, this does not include the other image URL types (`datasources/*`, Base64 URL etc.)
This PR changes the code to assess the other types of image URL.
The old code included an unintended feature where if the input included multiple image URLs in a string, e.g. `https://google.com, https://fliplet.com`, it was unable to return `['https://google.com', 'https://fliplet.com']`. There is no realistic scenario where this is useful so it shouldn't be a problem.

ID-1750 [Fix] Check more extensively for image URL types

---

css/build.css

@romanyosyfiv @inna-bieshulia
OD-483 https://weboo.atlassian.net/browse/OD-483
**Problem:** When the screen width is set to `min-width: 640px`, the margin is set to `margin-right: 0px`;
**Solution:** The given part has been removed and the indent on the right remains with the value `margin-right: 15px`.
https://storyxpress.co/video/kxq2ybvfrhsmqumd7

OD-483 [Fix] Fixed indentation of images in detailed view on tablet and web view for LFD entry

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-1789
This will allow 0 as filter value whereas it used to be excluded since it was falsey and excluded by `_.pickBy()`.

ID-1789 [Fix] Only exclude null, undefined or false values from filters

---

css/layout-css/news-feed-style.upload.css

@romanyosyfiv @inna-bieshulia
OD-677 https://weboo.atlassian.net/browse/OD-677
**Problem:** Wrong paddings are specified and because of this, the close button merges with the like and save buttons.
**Solution:** Added new paddings that corrected the position of the elements.
https://storyxpress.co/video/ky8pnz1hysxp6fi69

OD-677 [Fix] Adjusted paddings for correct display of the "close" button on tablet/web for News Feed layout

---

css/layout-css/small-card-style.upload.css

@romanyosyfiv @inna-bieshulia
OD-699 https://weboo.atlassian.net/browse/OD-699
**Problem:** Correct paddings are set only when there are images in the detailed view.
**Solution:** The same styles are added for detailed view without images.
https://storyxpress.co/video/kycj7m67lnj9yxsnj

OD-699 [Fix] Adjusted bookmark displaying on tablet/web for Directory layout without images

---

interface.html
js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-1674
Requires https://github.com/Fliplet/fliplet-api/pull/5123 for Android to download the file within the app and opening the files through the system instead of using the system browser to download files.

ID-1674 [Feat] Adds file mode when opening entries

---

js/utils.js

**Product areas affected**
Studio -> Login -> LFD -> Form
**What does this PR do?**
Implemented code, so after user login, LFD should show all entries in correct ASC order.
**JIRA ticket**
[click here](https://weboo.atlassian.net/browse/ID-3404)
**Result**
Uploading 3404.mp4…
**Checklist**
None
**Testing instructions**
None
**Deployment instructions**
None
**Author concerns**
None

ID-3404 [FIX] Ensure after login when LFD should show correct orders of created records

---

js/utils.js

Ref. https://weboo.atlassian.net/browse/ID-3806

ID-3806 [Fix] Prevent legacy MixItUp classes from clashing with generic class names

---

js/utils.js

| Title | Owner | PR |
| --- | --- | --- |
ID-3806 [Fix] Prevent legacy MixItUp classes from clashing with generic class names | TW | https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/730 |

ID-3806 Use a unique class pattern for legacy MixItUp classes (#730)

---

js/utils.js

Title | Owner | PR
-- | -- | --
ID-3806 [Fix] Prevent legacy MixItUp classes from clashing with generic class names | TW | https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/730

Release 20240218

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

This PR changes the way the file fields are rendered in detailed views. Instead of being rendered at the end, they are rendered according to defined field order.
[ID-4143](https://weboo.atlassian.net/browse/ID-4143)
[ID-4143]: https://weboo.atlassian.net/browse/ID-4143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ID-4143 [fix] LFD data view settings reordering fields file

---

js/layout-javascript/news-feed-code.js
js/layout-javascript/simple-list-code.js
js/layout-javascript/small-card-code.js

Follow up to https://github.com/Fliplet/fliplet-widget-dynamic-lists/pull/734
This PR changes the way the file fields are rendered in detailed views. Instead of being rendered at the end, they are rendered according to defined field order.
[ID-4143](https://weboo.atlassian.net/browse/ID-4143)
[ID-4143]: https://weboo.atlassian.net/browse/ID-4143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ID-4143 [fix] LFD data view file field order

---

js/query-parser.js

This PR ensures that once user has disabled search, filter or sort from LFD settings, no LFD query parameter should be parsed and processed.
- query-parser
[PS-940](https://weboo.atlassian.net/browse/PS-940) 
[PS-940]: https://weboo.atlassian.net/browse/PS-940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PS-940 [Fix] Ensure search, sort, filter querying does not work user has disabled it from settings
